[tool.poetry]
name = "oktoberfest"
version = "0.1.0"
description = ""
authors = ["WassimG <wassim.gabriel@tum.de>"]

[tool.poetry.dependencies]
python = "^3.8.0"
numpy = "^1.21.0"
pandas = "^1.3.0"
prosit-io = {git = "git@gitlab.lrz.de:compmass/prosit/tools/prosit_io.git", branch="develop"}
fundamentals = {git = "git@gitlab.lrz.de:compmass/prosit/tools/fundamentals.git", branch="develop"}
prosit_grpc = {git = "git@gitlab.lrz.de:proteomics/prosit_tools/prosit_grpc.git", branch="oktoberfest_revamp"}


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
